services:
  api:
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - 3000:3000

  postgres:
    image: postgres:15.1-alpine3.17
    restart: unless-stopped
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD', 'nc', '-z', 'localhost', '5432' ]
      interval: 5s
      timeout: 15s
      retries: 1
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres:
